config/routes.rb
Catalogue::Application.routes.draw do
  resources :projects
  resources :categories
  resources :programming_languages
  resources :licenses
  resources :countries

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/license.rb
class License < ApplicationRecord
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :developing_countries, class_name: 'Country', :join_table => :countries_developing_projects
  has_and_belongs_to_many :interested_by_countries, class_name: 'Country', :join_table => :countries_interested_in_projects
  has_and_belongs_to_many :used_by_countries, class_name: 'Country', :join_table => :countries_using_projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  def index
    @countries = Country.all
  end

  # GET /countries/1
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  def create
    @country = Country.new(country_params)

    if @country.save
      redirect_to @country, notice: 'Country was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /countries/1
  def update
    if @country.update(country_params)
      redirect_to @country, notice: 'Country was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /countries/1
  def destroy
    @country.destroy
    redirect_to countries_url, notice: 'Country was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def country_params
      params.require(:country).permit(:name, :slung, :flag)
    end
end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController
  before_action :set_license, only: [:show, :edit, :update, :destroy]

  # GET /licenses
  def index
    @licenses = License.all
  end

  # GET /licenses/1
  def show
  end

  # GET /licenses/new
  def new
    @license = License.new
  end

  # GET /licenses/1/edit
  def edit
  end

  # POST /licenses
  def create
    @license = License.new(license_params)

    if @license.save
      redirect_to @license, notice: 'License was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /licenses/1
  def update
    if @license.update(license_params)
      redirect_to @license, notice: 'License was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /licenses/1
  def destroy
    @license.destroy
    redirect_to licenses_url, notice: 'License was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_license
      @license = License.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def license_params
      params.require(:license).permit(:name, :short_name, :url)
    end
end

app/controllers/programming_languages_controller.rb
class ProgrammingLanguagesController < ApplicationController
  before_action :set_programming_language, only: [:show, :edit, :update, :destroy]

  # GET /programming_languages
  def index
    @programming_languages = ProgrammingLanguage.all
  end

  # GET /programming_languages/1
  def show
  end

  # GET /programming_languages/new
  def new
    @programming_language = ProgrammingLanguage.new
  end

  # GET /programming_languages/1/edit
  def edit
  end

  # POST /programming_languages
  def create
    @programming_language = ProgrammingLanguage.new(programming_language_params)

    if @programming_language.save
      redirect_to @programming_language, notice: 'Programming language was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /programming_languages/1
  def update
    if @programming_language.update(programming_language_params)
      redirect_to @programming_language, notice: 'Programming language was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /programming_languages/1
  def destroy
    @programming_language.destroy
    redirect_to programming_languages_url, notice: 'Programming language was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_programming_language
      @programming_language = ProgrammingLanguage.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def programming_language_params
      params.require(:programming_language).permit(:name, :url)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :description, :developing_countries_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/programming_languages_helper.rb
module ProgrammingLanguagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/countries/_form.html.erb
<%= form_for(country) do |f| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slung %>
    <%= f.text_field :slung %>
  </div>

  <div class="field">
    <%= f.label :flag %>
    <%= f.text_field :flag %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Slung</th>
      <th>Flag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.slung %></td>
        <td><%= country.flag %></td>
        <td><%= link_to 'Show', country %></td>
        <td><%= link_to 'Edit', edit_country_path(country) %></td>
        <td><%= link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_country_path %>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Slung:</strong>
  <%= @country.slung %>
</p>

<p>
  <strong>Flag:</strong>
  <%= @country.flag %>
</p>

<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catalogue</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/licenses/_form.html.erb
<%= form_for(license) do |f| %>
  <% if license.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(license.errors.count, "error") %> prohibited this license from being saved:</h2>

      <ul>
      <% license.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :short_name %>
    <%= f.text_field :short_name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/licenses/edit.html.erb
<h1>Editing License</h1>

<%= render 'form', license: @license %>

<%= link_to 'Show', @license %> |
<%= link_to 'Back', licenses_path %>

app/views/licenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Licenses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @licenses.each do |license| %>
      <tr>
        <td><%= license.name %></td>
        <td><%= license.short_name %></td>
        <td><%= license.url %></td>
        <td><%= link_to 'Show', license %></td>
        <td><%= link_to 'Edit', edit_license_path(license) %></td>
        <td><%= link_to 'Destroy', license, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New License', new_license_path %>

app/views/licenses/new.html.erb
<h1>New License</h1>

<%= render 'form', license: @license %>

<%= link_to 'Back', licenses_path %>

app/views/licenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @license.name %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @license.short_name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @license.url %>
</p>

<%= link_to 'Edit', edit_license_path(@license) %> |
<%= link_to 'Back', licenses_path %>

app/views/programming_languages/_form.html.erb
<%= form_for(programming_language) do |f| %>
  <% if programming_language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(programming_language.errors.count, "error") %> prohibited this programming_language from being saved:</h2>

      <ul>
      <% programming_language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programming_languages/edit.html.erb
<h1>Editing Programming Language</h1>

<%= render 'form', programming_language: @programming_language %>

<%= link_to 'Show', @programming_language %> |
<%= link_to 'Back', programming_languages_path %>

app/views/programming_languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Programming Languages</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programming_languages.each do |programming_language| %>
      <tr>
        <td><%= programming_language.name %></td>
        <td><%= programming_language.url %></td>
        <td><%= link_to 'Show', programming_language %></td>
        <td><%= link_to 'Edit', edit_programming_language_path(programming_language) %></td>
        <td><%= link_to 'Destroy', programming_language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Programming Language', new_programming_language_path %>

app/views/programming_languages/new.html.erb
<h1>New Programming Language</h1>

<%= render 'form', programming_language: @programming_language %>

<%= link_to 'Back', programming_languages_path %>

app/views/programming_languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @programming_language.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @programming_language.url %>
</p>

<%= link_to 'Edit', edit_programming_language_path(@programming_language) %> |
<%= link_to 'Back', programming_languages_path %>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :developing_countries_id %>
    <%= f.text_field :developing_countries_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Developing countries</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.developing_countries %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Developing countries:</strong>
  <%= @project.developing_countries %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>